spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: testuser
    password: test1234
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace  # 변수값 출력
    org.apache.tomcat: info
    com.tpirates.apitest: trace
    org.springframework.transaction: trace  # 트랜젝션 로그 활성화


server:
  compression:
    enabled: true
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: true
      directory: logs/
    basedir: /damb-server/logs/tomcat
    max-http-form-post-size: 50MB
  servlet:
    context-path: /
  port: 9000